// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDO14be6i2w-CQVFu0_AvokAbKMC_QaluY',
    appId: '1:774887069540:web:962804cdad3fd00f88cc71',
    messagingSenderId: '774887069540',
    projectId: 'plumora-f69ca',
    authDomain: 'plumora-f69ca.firebaseapp.com',
    storageBucket: 'plumora-f69ca.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlKDlYhYzsqBtr7NztGDqd9vgg1N2d79w',
    appId: '1:774887069540:android:05acc3679c97a36888cc71',
    messagingSenderId: '774887069540',
    projectId: 'plumora-f69ca',
    storageBucket: 'plumora-f69ca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUJoLvi00nl8AVEqZOVDNQyCjhZ7hOLM8',
    appId: '1:774887069540:ios:fa49473bd200e5e488cc71',
    messagingSenderId: '774887069540',
    projectId: 'plumora-f69ca',
    storageBucket: 'plumora-f69ca.firebasestorage.app',
    iosBundleId: 'com.example.plumora',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUJoLvi00nl8AVEqZOVDNQyCjhZ7hOLM8',
    appId: '1:774887069540:ios:fa49473bd200e5e488cc71',
    messagingSenderId: '774887069540',
    projectId: 'plumora-f69ca',
    storageBucket: 'plumora-f69ca.firebasestorage.app',
    iosBundleId: 'com.example.plumora',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDO14be6i2w-CQVFu0_AvokAbKMC_QaluY',
    appId: '1:774887069540:web:414c871cb91b00f888cc71',
    messagingSenderId: '774887069540',
    projectId: 'plumora-f69ca',
    authDomain: 'plumora-f69ca.firebaseapp.com',
    storageBucket: 'plumora-f69ca.firebasestorage.app',
  );
}
